/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { api } from '../../../lib/server';
import type { ErrorType } from '../../../lib/server';
import type {
  CreatePostResponse,
  CreateRecruitmentPostRequest,
  GetRecruitmentPostsParams,
  PaginatedGetPostsResponse,
  UpdateRecruitmentPostRequest,
  UpdateRecruitmentStatusRequest,
} from '../types';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getRecruitmentPostsResponse200 = {
  data: PaginatedGetPostsResponse;
  status: 200;
};

export type getRecruitmentPostsResponseSuccess =
  getRecruitmentPostsResponse200 & {
    headers: Headers;
  };
export type getRecruitmentPostsResponse = getRecruitmentPostsResponseSuccess;

export const getGetRecruitmentPostsUrl = (
  params?: GetRecruitmentPostsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/recruitment-posts?${stringifiedParams}`
    : `/recruitment-posts`;
};

/**
 * 일반 피드와 분리된 구인글 목록을 조회합니다.
 * @summary 구인글 목록 조회
 */
export const getRecruitmentPosts = async (
  params?: GetRecruitmentPostsParams,
  options?: RequestInit,
): Promise<getRecruitmentPostsResponse> => {
  return api<getRecruitmentPostsResponse>(getGetRecruitmentPostsUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getGetRecruitmentPostsInfiniteQueryKey = (
  params?: GetRecruitmentPostsParams,
) => {
  return [
    'infinite',
    `/recruitment-posts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetRecruitmentPostsQueryKey = (
  params?: GetRecruitmentPostsParams,
) => {
  return [`/recruitment-posts`, ...(params ? [params] : [])] as const;
};

export const getGetRecruitmentPostsInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    GetRecruitmentPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData,
        QueryKey,
        GetRecruitmentPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRecruitmentPostsInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    QueryKey,
    GetRecruitmentPostsParams['after']
  > = ({ signal, pageParam }) =>
    getRecruitmentPosts(
      { ...params, after: pageParam ?? params?.['after'] },
      { signal, ...requestOptions },
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    TError,
    TData,
    QueryKey,
    GetRecruitmentPostsParams['after']
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecruitmentPostsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecruitmentPosts>>
>;
export type GetRecruitmentPostsInfiniteQueryError = ErrorType<unknown>;

export function useGetRecruitmentPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    GetRecruitmentPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetRecruitmentPostsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData,
        QueryKey,
        GetRecruitmentPostsParams['after']
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecruitmentPosts>>,
          TError,
          Awaited<ReturnType<typeof getRecruitmentPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecruitmentPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    GetRecruitmentPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData,
        QueryKey,
        GetRecruitmentPostsParams['after']
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecruitmentPosts>>,
          TError,
          Awaited<ReturnType<typeof getRecruitmentPosts>>,
          QueryKey
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecruitmentPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    GetRecruitmentPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData,
        QueryKey,
        GetRecruitmentPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 구인글 목록 조회
 */

export function useGetRecruitmentPostsInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    GetRecruitmentPostsParams['after']
  >,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData,
        QueryKey,
        GetRecruitmentPostsParams['after']
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecruitmentPostsInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetRecruitmentPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getRecruitmentPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetRecruitmentPostsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getRecruitmentPosts>>
  > = ({ signal }) =>
    getRecruitmentPosts(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRecruitmentPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRecruitmentPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getRecruitmentPosts>>
>;
export type GetRecruitmentPostsQueryError = ErrorType<unknown>;

export function useGetRecruitmentPosts<
  TData = Awaited<ReturnType<typeof getRecruitmentPosts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetRecruitmentPostsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecruitmentPosts>>,
          TError,
          Awaited<ReturnType<typeof getRecruitmentPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecruitmentPosts<
  TData = Awaited<ReturnType<typeof getRecruitmentPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRecruitmentPosts>>,
          TError,
          Awaited<ReturnType<typeof getRecruitmentPosts>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRecruitmentPosts<
  TData = Awaited<ReturnType<typeof getRecruitmentPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 구인글 목록 조회
 */

export function useGetRecruitmentPosts<
  TData = Awaited<ReturnType<typeof getRecruitmentPosts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetRecruitmentPostsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getRecruitmentPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetRecruitmentPostsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export type createRecruitmentPostResponse201 = {
  data: CreatePostResponse;
  status: 201;
};

export type createRecruitmentPostResponseSuccess =
  createRecruitmentPostResponse201 & {
    headers: Headers;
  };
export type createRecruitmentPostResponse =
  createRecruitmentPostResponseSuccess;

export const getCreateRecruitmentPostUrl = () => {
  return `/recruitment-posts`;
};

/**
 * 개인 LONG 게시글을 기반으로 구인글을 생성합니다.
 * @summary 구인글 생성
 */
export const createRecruitmentPost = async (
  createRecruitmentPostRequest?: CreateRecruitmentPostRequest,
  options?: RequestInit,
): Promise<createRecruitmentPostResponse> => {
  return api<createRecruitmentPostResponse>(getCreateRecruitmentPostUrl(), {
    ...options,
    method: 'POST',
    headers: {
      'Content-Type': 'application/json;charset=UTF-8',
      ...options?.headers,
    },
    body: JSON.stringify(createRecruitmentPostRequest),
  });
};

export const getCreateRecruitmentPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRecruitmentPost>>,
    TError,
    { data?: CreateRecruitmentPostRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRecruitmentPost>>,
  TError,
  { data?: CreateRecruitmentPostRequest },
  TContext
> => {
  const mutationKey = ['createRecruitmentPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRecruitmentPost>>,
    { data?: CreateRecruitmentPostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createRecruitmentPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateRecruitmentPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createRecruitmentPost>>
>;
export type CreateRecruitmentPostMutationBody =
  | CreateRecruitmentPostRequest
  | undefined;
export type CreateRecruitmentPostMutationError = ErrorType<unknown>;

/**
 * @summary 구인글 생성
 */
export const useCreateRecruitmentPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRecruitmentPost>>,
      TError,
      { data?: CreateRecruitmentPostRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createRecruitmentPost>>,
  TError,
  { data?: CreateRecruitmentPostRequest },
  TContext
> => {
  return useMutation(
    getCreateRecruitmentPostMutationOptions(options),
    queryClient,
  );
};
export type updateRecruitmentPostResponse204 = {
  data: void;
  status: 204;
};

export type updateRecruitmentPostResponseSuccess =
  updateRecruitmentPostResponse204 & {
    headers: Headers;
  };
export type updateRecruitmentPostResponse =
  updateRecruitmentPostResponseSuccess;

export const getUpdateRecruitmentPostUrl = (postId: string) => {
  return `/recruitment-posts/${postId}`;
};

/**
 * 작성자가 구인글 본문과 메타데이터를 수정합니다.
 * @summary 구인글 수정
 */
export const updateRecruitmentPost = async (
  postId: string,
  updateRecruitmentPostRequest?: UpdateRecruitmentPostRequest,
  options?: RequestInit,
): Promise<updateRecruitmentPostResponse> => {
  return api<updateRecruitmentPostResponse>(
    getUpdateRecruitmentPostUrl(postId),
    {
      ...options,
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json;charset=UTF-8',
        ...options?.headers,
      },
      body: JSON.stringify(updateRecruitmentPostRequest),
    },
  );
};

export const getUpdateRecruitmentPostMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRecruitmentPost>>,
    TError,
    { postId: string; data?: UpdateRecruitmentPostRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRecruitmentPost>>,
  TError,
  { postId: string; data?: UpdateRecruitmentPostRequest },
  TContext
> => {
  const mutationKey = ['updateRecruitmentPost'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRecruitmentPost>>,
    { postId: string; data?: UpdateRecruitmentPostRequest }
  > = (props) => {
    const { postId, data } = props ?? {};

    return updateRecruitmentPost(postId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRecruitmentPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRecruitmentPost>>
>;
export type UpdateRecruitmentPostMutationBody =
  | UpdateRecruitmentPostRequest
  | undefined;
export type UpdateRecruitmentPostMutationError = ErrorType<unknown>;

/**
 * @summary 구인글 수정
 */
export const useUpdateRecruitmentPost = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRecruitmentPost>>,
      TError,
      { postId: string; data?: UpdateRecruitmentPostRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateRecruitmentPost>>,
  TError,
  { postId: string; data?: UpdateRecruitmentPostRequest },
  TContext
> => {
  return useMutation(
    getUpdateRecruitmentPostMutationOptions(options),
    queryClient,
  );
};
export type updateRecruitmentStatusResponse204 = {
  data: void;
  status: 204;
};

export type updateRecruitmentStatusResponseSuccess =
  updateRecruitmentStatusResponse204 & {
    headers: Headers;
  };
export type updateRecruitmentStatusResponse =
  updateRecruitmentStatusResponseSuccess;

export const getUpdateRecruitmentStatusUrl = (postId: string) => {
  return `/recruitment-posts/${postId}/status`;
};

/**
 * 작성자가 구인글을 마감하거나 다시 엽니다.
 * @summary 모집 상태 변경
 */
export const updateRecruitmentStatus = async (
  postId: string,
  updateRecruitmentStatusRequest?: UpdateRecruitmentStatusRequest,
  options?: RequestInit,
): Promise<updateRecruitmentStatusResponse> => {
  return api<updateRecruitmentStatusResponse>(
    getUpdateRecruitmentStatusUrl(postId),
    {
      ...options,
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json;charset=UTF-8',
        ...options?.headers,
      },
      body: JSON.stringify(updateRecruitmentStatusRequest),
    },
  );
};

export const getUpdateRecruitmentStatusMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRecruitmentStatus>>,
    TError,
    { postId: string; data?: UpdateRecruitmentStatusRequest },
    TContext
  >;
  request?: SecondParameter<typeof api>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRecruitmentStatus>>,
  TError,
  { postId: string; data?: UpdateRecruitmentStatusRequest },
  TContext
> => {
  const mutationKey = ['updateRecruitmentStatus'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRecruitmentStatus>>,
    { postId: string; data?: UpdateRecruitmentStatusRequest }
  > = (props) => {
    const { postId, data } = props ?? {};

    return updateRecruitmentStatus(postId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateRecruitmentStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateRecruitmentStatus>>
>;
export type UpdateRecruitmentStatusMutationBody =
  | UpdateRecruitmentStatusRequest
  | undefined;
export type UpdateRecruitmentStatusMutationError = ErrorType<unknown>;

/**
 * @summary 모집 상태 변경
 */
export const useUpdateRecruitmentStatus = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRecruitmentStatus>>,
      TError,
      { postId: string; data?: UpdateRecruitmentStatusRequest },
      TContext
    >;
    request?: SecondParameter<typeof api>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateRecruitmentStatus>>,
  TError,
  { postId: string; data?: UpdateRecruitmentStatusRequest },
  TContext
> => {
  return useMutation(
    getUpdateRecruitmentStatusMutationOptions(options),
    queryClient,
  );
};
