/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type CreateRecruitmentPostRequestReferencedPostIdsItem =
  | { [key: string]: unknown }
  | boolean
  | string
  | number;
