/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { CreateRecruitmentPostRequestContentMediaIdsItem } from './CreateRecruitmentPostRequestContentMediaIdsItem';

/**
 * 모집 내용
 */
export type CreateRecruitmentPostRequestContent = {
  /** Tiptap JSON 본문 */
  json: string;
  /**
   * 본문에서 사용한 미디어 ID 목록
   * @nullable
   */
  mediaIds?: CreateRecruitmentPostRequestContentMediaIdsItem[] | null;
  /** 본문 텍스트 */
  text: string;
};
