/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 경력 수준
 */
export type CreateRecruitmentPostRequestExperienceLevel =
  (typeof CreateRecruitmentPostRequestExperienceLevel)[keyof typeof CreateRecruitmentPostRequestExperienceLevel];

export const CreateRecruitmentPostRequestExperienceLevel = {
  Any: 'ANY',
  Entry: 'ENTRY',
  Junior: 'JUNIOR',
  Mid: 'MID',
  Senior: 'SENIOR',
} as const;
