/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 근무 방식
 */
export type CreateRecruitmentPostRequestWorkMode =
  (typeof CreateRecruitmentPostRequestWorkMode)[keyof typeof CreateRecruitmentPostRequestWorkMode];

export const CreateRecruitmentPostRequestWorkMode = {
  Remote: 'REMOTE',
  Hybrid: 'HYBRID',
  Onsite: 'ONSITE',
} as const;
