/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export interface CsrfToken {
  /** CSRF 토큰 요청 헤더 이름 */
  headerName: string;
  /** CSRF 토큰 요청 파라미터 이름 */
  parameterName: string;
  /** CSRF 토큰 값 */
  token: string;
}
