/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 경력 수준
 * @nullable
 */
export type GetCollectionPostsResponsePostsNodesItemContentPostRecruitmentExperienceLevel =

    | (typeof GetCollectionPostsResponsePostsNodesItemContentPostRecruitmentExperienceLevel)[keyof typeof GetCollectionPostsResponsePostsNodesItemContentPostRecruitmentExperienceLevel]
    | null;

export const GetCollectionPostsResponsePostsNodesItemContentPostRecruitmentExperienceLevel =
  {
    Any: 'ANY',
    Entry: 'ENTRY',
    Junior: 'JUNIOR',
    Mid: 'MID',
    Senior: 'SENIOR',
  } as const;
