/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel } from './GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel';
import type { GetCollectionPostsResponsePostsNodesItemContentPostAuthor } from './GetCollectionPostsResponsePostsNodesItemContentPostAuthor';
import type { GetCollectionPostsResponsePostsNodesItemContentPostPreviewMediaItem } from './GetCollectionPostsResponsePostsNodesItemContentPostPreviewMediaItem';
import type { GetCollectionPostsResponsePostsNodesItemContentPostProject } from './GetCollectionPostsResponsePostsNodesItemContentPostProject';
import type { GetCollectionPostsResponsePostsNodesItemContentPostRecruitment } from './GetCollectionPostsResponsePostsNodesItemContentPostRecruitment';
import type { GetCollectionPostsResponsePostsNodesItemContentPostScope } from './GetCollectionPostsResponsePostsNodesItemContentPostScope';
import type { GetCollectionPostsResponsePostsNodesItemContentPostStatus } from './GetCollectionPostsResponsePostsNodesItemContentPostStatus';
import type { GetCollectionPostsResponsePostsNodesItemContentPostTagsItem } from './GetCollectionPostsResponsePostsNodesItemContentPostTagsItem';
import type { GetCollectionPostsResponsePostsNodesItemContentPostType } from './GetCollectionPostsResponsePostsNodesItemContentPostType';

/**
 * 게시글 요약 (뷰어가 열람 가능한 경우에만 존재. 없으면 삭제·비공개로 열람 불가한 tombstone 이다. 본문 열람 수준은 post.accessLevel 로 구분한다)
 */
export type GetCollectionPostsResponsePostsNodesItemContentPost = {
  /**
   * 게시물 내용의 일반 텍스트 미리보기
   * @nullable
   */
  preview?: string | null;
  /**
   * 게시물 커버 이미지 URL (없으면 없음)
   * @nullable
   */
  coverImageUrl?: string | null;
  /** 소속 프로젝트 정보 */
  project?: GetCollectionPostsResponsePostsNodesItemContentPostProject;
  /**
   * Number of Likes
   * @nullable
   */
  likeCount?: number | null;
  /**
   * Post Type
   * @nullable
   */
  type?: GetCollectionPostsResponsePostsNodesItemContentPostType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /**
   * Whether the current user liked this post
   * @nullable
   */
  liked?: boolean | null;
  /**
   * Whether the requesting user is the author of this post
   * @nullable
   */
  isAuthor?: boolean | null;
  /**
   * 게시글이 프로젝트 대시보드에 고정된 시각 (고정되지 않은 경우 없음)
   * @nullable
   */
  pinnedAt?: string | null;
  /**
   * Creation Timestamp
   * @nullable
   */
  createdAt?: string | null;
  /** 구인글 메타데이터 (일반 게시글에는 없음) */
  recruitment?: GetCollectionPostsResponsePostsNodesItemContentPostRecruitment;
  /**
   * 게시글 공개 범위
   * @nullable
   */
  scope?: GetCollectionPostsResponsePostsNodesItemContentPostScope;
  /**
   * 게시물에 첨부된 전체 미디어 수
   * @nullable
   */
  mediaCount?: number | null;
  /**
   * 요청자가 이 게시글을 삭제할 수 있는지 여부 (작성자, 플랫폼 관리자(개인 게시글), 프로젝트 관리자(프로젝트 게시글))
   * @nullable
   */
  canDelete?: boolean | null;
  /**
   * 요청자가 이 게시글에 댓글을 작성할 수 있는지 여부 (프로젝트 게시글은 팀원만 가능)
   * @nullable
   */
  canComment?: boolean | null;
  /**
   * Post ID
   * @nullable
   */
  id?: number | null;
  /**
   * Post Slug
   * @nullable
   */
  slug?: string | null;
  /**
   * Last Updated Timestamp
   * @nullable
   */
  updatedAt?: string | null;
  /**
   * Whether the question post has been resolved
   * @nullable
   */
  resolved?: boolean | null;
  /**
   * 게시물 본문의 단어 수
   * @nullable
   */
  wordCount?: number | null;
  /**
   * 요청자의 열람 수준 (FULL: 본문까지 열람, PREVIEW: 유료 게이트로 본문 잠김)
   * @nullable
   */
  accessLevel?: GetCollectionPostsResponsePostsNodesItemContentPostAccessLevel;
  /**
   * 이 글을 만든 에이전트 클라이언트의 이름. 사람이 직접 쓴 글에는 없다
   * @nullable
   */
  createdViaClientName?: string | null;
  /**
   * Whether the current user bookmarked this post
   * @nullable
   */
  bookmarked?: boolean | null;
  /** 작성자 정보 */
  author?: GetCollectionPostsResponsePostsNodesItemContentPostAuthor;
  /** 게시물에 달린 태그 목록 */
  tags?: GetCollectionPostsResponsePostsNodesItemContentPostTagsItem[];
  /**
   * Number of Comments
   * @nullable
   */
  commentCount?: number | null;
  /**
   * 게시글이 어떤 시리즈에 속해 있는지 여부
   * @nullable
   */
  isSeriesPost?: boolean | null;
  /** 미리보기용 첨부 이미지 목록 (최대 3개). 이미지가 아닌 첨부 파일은 포함되지 않는다 */
  previewMedia?: GetCollectionPostsResponsePostsNodesItemContentPostPreviewMediaItem[];
  /**
   * Post Status
   * @nullable
   */
  status?: GetCollectionPostsResponsePostsNodesItemContentPostStatus;
};
