/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Project Information
 */
export type GetFeedResponseItemsNodesItemContentProject = {
  /** Project Name */
  name: string;
  /** Project Handle */
  handle: string;
};
