/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 초대받는 역할
 */
export type GetMyProjectInvitationsResponseInvitationsItemRole =
  (typeof GetMyProjectInvitationsResponseInvitationsItemRole)[keyof typeof GetMyProjectInvitationsResponseInvitationsItemRole];

export const GetMyProjectInvitationsResponseInvitationsItemRole = {
  Admin: 'ADMIN',
  Member: 'MEMBER',
} as const;
