/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetMyProjectInvitationsResponseInvitationsItemRole } from './GetMyProjectInvitationsResponseInvitationsItemRole';

export type GetMyProjectInvitationsResponseInvitationsItem = {
  /** 초대한 유저의 핸들 */
  inviterHandle: string;
  /** 초대받는 역할 */
  role: GetMyProjectInvitationsResponseInvitationsItemRole;
  /** 초대 ID */
  id: number;
  /** 프로젝트 이름 */
  projectName: string;
  /** 초대 만료 시각 */
  expiresAt: string;
  /** 초대한 유저의 이름 */
  inviterName: string;
  /** 프로젝트 핸들 */
  projectHandle: string;
  /** 초대 토큰 */
  token: string;
};
