/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseAuthor } from './GetPostResponseAuthor';
import type { GetPostResponseContent } from './GetPostResponseContent';
import type { GetPostResponseProject } from './GetPostResponseProject';
import type { GetPostResponseScope } from './GetPostResponseScope';
import type { GetPostResponseStatus } from './GetPostResponseStatus';
import type { GetPostResponseType } from './GetPostResponseType';

export interface GetPostResponse {
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** Author Information */
  author: GetPostResponseAuthor;
  /** Project Information */
  project?: GetPostResponseProject;
  /** Number of Likes */
  likeCount: number;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Post Type */
  type: GetPostResponseType;
  /** Post Content */
  content: GetPostResponseContent;
  /** Number of Comments */
  commentCount: number;
  /** Creation Timestamp */
  createdAt: string;
  /** Post Scope */
  scope: GetPostResponseScope;
  /** Post ID */
  id: number;
  /** Post Slug */
  slug: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
  /** Post Status */
  status: GetPostResponseStatus;
}
