/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsItemRecruitmentEmploymentType } from './GetPostsResponsePostsItemRecruitmentEmploymentType';
import type { GetPostsResponsePostsItemRecruitmentExperienceLevel } from './GetPostsResponsePostsItemRecruitmentExperienceLevel';
import type { GetPostsResponsePostsItemRecruitmentStatus } from './GetPostsResponsePostsItemRecruitmentStatus';
import type { GetPostsResponsePostsItemRecruitmentWorkMode } from './GetPostsResponsePostsItemRecruitmentWorkMode';

/**
 * 구인글 메타데이터 (일반 게시글에는 없음)
 */
export type GetPostsResponsePostsItemRecruitment = {
  /**
   * 경력 수준
   * @nullable
   */
  experienceLevel?: GetPostsResponsePostsItemRecruitmentExperienceLevel;
  /**
   * 근무 방식
   * @nullable
   */
  workMode?: GetPostsResponsePostsItemRecruitmentWorkMode;
  /**
   * 고용 형태
   * @nullable
   */
  employmentType?: GetPostsResponsePostsItemRecruitmentEmploymentType;
  /**
   * 근무 지역
   * @nullable
   */
  location?: string | null;
  /**
   * 모집 마감 시각
   * @nullable
   */
  closesAt?: string | null;
  /**
   * 모집 상태
   * @nullable
   */
  status?: GetPostsResponsePostsItemRecruitmentStatus;
};
