/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseContentMediaItem } from './GetPostResponseContentMediaItem';
import type { GetPostResponseContentTagsItem } from './GetPostResponseContentTagsItem';

/**
 * Post Content
 */
export type GetPostResponseContent = {
  /** Post Content JSON */
  json: string;
  /** Media attached to the post */
  media: GetPostResponseContentMediaItem[];
  /** 태그 목록 */
  tags: GetPostResponseContentTagsItem[];
};
