/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostResponseSummaryRecruitmentEmploymentType } from './GetPostResponseSummaryRecruitmentEmploymentType';
import type { GetPostResponseSummaryRecruitmentExperienceLevel } from './GetPostResponseSummaryRecruitmentExperienceLevel';
import type { GetPostResponseSummaryRecruitmentStatus } from './GetPostResponseSummaryRecruitmentStatus';
import type { GetPostResponseSummaryRecruitmentWorkMode } from './GetPostResponseSummaryRecruitmentWorkMode';

/**
 * 구인글 메타데이터 (일반 게시글에는 없음)
 */
export type GetPostResponseSummaryRecruitment = {
  /**
   * 경력 수준
   * @nullable
   */
  experienceLevel?: GetPostResponseSummaryRecruitmentExperienceLevel;
  /**
   * 근무 방식
   * @nullable
   */
  workMode?: GetPostResponseSummaryRecruitmentWorkMode;
  /**
   * 고용 형태
   * @nullable
   */
  employmentType?: GetPostResponseSummaryRecruitmentEmploymentType;
  /**
   * 근무 지역
   * @nullable
   */
  location?: string | null;
  /**
   * 모집 마감 시각
   * @nullable
   */
  closesAt?: string | null;
  /**
   * 모집 상태
   * @nullable
   */
  status?: GetPostResponseSummaryRecruitmentStatus;
};
