/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 고용 형태
 * @nullable
 */
export type GetPostsResponsePostsItemRecruitmentEmploymentType =
  | (typeof GetPostsResponsePostsItemRecruitmentEmploymentType)[keyof typeof GetPostsResponsePostsItemRecruitmentEmploymentType]
  | null;

export const GetPostsResponsePostsItemRecruitmentEmploymentType = {
  FullTime: 'FULL_TIME',
  PartTime: 'PART_TIME',
  Contract: 'CONTRACT',
  Internship: 'INTERNSHIP',
  FreelanceProject: 'FREELANCE_PROJECT',
} as const;
