/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 초대받은 유저의 역할
 */
export type GetProjectInvitationsResponseInvitationsItemRole =
  (typeof GetProjectInvitationsResponseInvitationsItemRole)[keyof typeof GetProjectInvitationsResponseInvitationsItemRole];

export const GetProjectInvitationsResponseInvitationsItemRole = {
  Admin: 'ADMIN',
  Member: 'MEMBER',
} as const;
