/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 근무 방식
 * @nullable
 */
export type GetPostsResponsePostsItemRecruitmentWorkMode =
  | (typeof GetPostsResponsePostsItemRecruitmentWorkMode)[keyof typeof GetPostsResponsePostsItemRecruitmentWorkMode]
  | null;

export const GetPostsResponsePostsItemRecruitmentWorkMode = {
  Remote: 'REMOTE',
  Hybrid: 'HYBRID',
  Onsite: 'ONSITE',
} as const;
