/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetProjectRecommendationsResponseProjectsItemJoinPolicy } from './GetProjectRecommendationsResponseProjectsItemJoinPolicy';

export type GetProjectRecommendationsResponseProjectsItem = {
  /** 생성 시각 */
  createdAt: string;
  /**
   * 프로젝트 웹사이트
   * @nullable
   */
  website?: string | null;
  /** 프로젝트 이름 */
  name: string;
  /** 공개 여부 */
  isPublic: boolean;
  /**
   * 프로젝트 설명
   * @nullable
   */
  description?: string | null;
  /**
   * 프로젝트 규칙
   * @nullable
   */
  rules?: string | null;
  /** 프로젝트 핸들 */
  handle: string;
  /**
   * 프로젝트 아이콘 URL
   * @nullable
   */
  iconUrl?: string | null;
  /** 프로젝트 참여 정책 */
  joinPolicy: GetProjectRecommendationsResponseProjectsItemJoinPolicy;
  /** 프로젝트 팔로워 수 */
  followerCount: number;
};
