/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { GetPostsResponsePostsNodesItemContentAuthor } from './GetPostsResponsePostsNodesItemContentAuthor';
import type { GetPostsResponsePostsNodesItemContentProject } from './GetPostsResponsePostsNodesItemContentProject';
import type { GetPostsResponsePostsNodesItemContentScope } from './GetPostsResponsePostsNodesItemContentScope';
import type { GetPostsResponsePostsNodesItemContentStatus } from './GetPostsResponsePostsNodesItemContentStatus';
import type { GetPostsResponsePostsNodesItemContentType } from './GetPostsResponsePostsNodesItemContentType';

/**
 * Node Content
 */
export type GetPostsResponsePostsNodesItemContent = {
  /** Creation Timestamp */
  createdAt: string;
  /** Author Information */
  author: GetPostsResponsePostsNodesItemContentAuthor;
  /** Post Scope */
  scope: GetPostsResponsePostsNodesItemContentScope;
  /** Project Information */
  project?: GetPostsResponsePostsNodesItemContentProject;
  /** Post ID */
  id: number;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Post Type */
  type: GetPostsResponsePostsNodesItemContentType;
  /** Post Content */
  content: string;
  /** Post Slug */
  slug: string;
  /** Post Status */
  status: GetPostsResponsePostsNodesItemContentStatus;
};
