/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 경력 수준
 * @nullable
 */
export type GetPostResponseSummaryRecruitmentExperienceLevel =
  | (typeof GetPostResponseSummaryRecruitmentExperienceLevel)[keyof typeof GetPostResponseSummaryRecruitmentExperienceLevel]
  | null;

export const GetPostResponseSummaryRecruitmentExperienceLevel = {
  Any: 'ANY',
  Entry: 'ENTRY',
  Junior: 'JUNIOR',
  Mid: 'MID',
  Senior: 'SENIOR',
} as const;
