/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 모집 상태
 * @nullable
 */
export type GetPostResponseSummaryRecruitmentStatus =
  | (typeof GetPostResponseSummaryRecruitmentStatus)[keyof typeof GetPostResponseSummaryRecruitmentStatus]
  | null;

export const GetPostResponseSummaryRecruitmentStatus = {
  Open: 'OPEN',
  Closed: 'CLOSED',
} as const;
