/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 모집 상태
 * @nullable
 */
export type GetPostsResponsePostsItemRecruitmentStatus =
  | (typeof GetPostsResponsePostsItemRecruitmentStatus)[keyof typeof GetPostsResponsePostsItemRecruitmentStatus]
  | null;

export const GetPostsResponsePostsItemRecruitmentStatus = {
  Open: 'OPEN',
  Closed: 'CLOSED',
} as const;
