/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * Post Status
 */
export type GetPostResponseStatus =
  (typeof GetPostResponseStatus)[keyof typeof GetPostResponseStatus];

export const GetPostResponseStatus = {
  Draft: 'DRAFT',
  Published: 'PUBLISHED',
} as const;
