/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type GetRecruitmentPostsParams = {
  /**
   * 모집 상태 (미지정 시 전체)
   */
  status?: string;
  /**
   * 고용 형태
   */
  employmentType?: string;
  /**
   * 근무 방식
   */
  workMode?: string;
  /**
   * 경력 수준
   */
  experienceLevel?: string;
  /**
   * 근무 지역 검색어
   */
  location?: string;
  /**
   * 기술 태그 이름
   */
  tag?: string;
  /**
   * 제목 또는 미리보기 검색어
   */
  query?: string;
  /**
   * 정방향 조회 개수
   */
  first?: string;
  /**
   * 정방향 커서
   */
  after?: string;
  /**
   * 역방향 조회 개수
   */
  last?: string;
  /**
   * 역방향 커서
   */
  before?: string;
};
