/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedGetPostsResponsePostsNodesItemContentAccessLevel } from './PaginatedGetPostsResponsePostsNodesItemContentAccessLevel';
import type { PaginatedGetPostsResponsePostsNodesItemContentAuthor } from './PaginatedGetPostsResponsePostsNodesItemContentAuthor';
import type { PaginatedGetPostsResponsePostsNodesItemContentPreviewMediaItem } from './PaginatedGetPostsResponsePostsNodesItemContentPreviewMediaItem';
import type { PaginatedGetPostsResponsePostsNodesItemContentProject } from './PaginatedGetPostsResponsePostsNodesItemContentProject';
import type { PaginatedGetPostsResponsePostsNodesItemContentRecruitment } from './PaginatedGetPostsResponsePostsNodesItemContentRecruitment';
import type { PaginatedGetPostsResponsePostsNodesItemContentScope } from './PaginatedGetPostsResponsePostsNodesItemContentScope';
import type { PaginatedGetPostsResponsePostsNodesItemContentStatus } from './PaginatedGetPostsResponsePostsNodesItemContentStatus';
import type { PaginatedGetPostsResponsePostsNodesItemContentTagsItem } from './PaginatedGetPostsResponsePostsNodesItemContentTagsItem';
import type { PaginatedGetPostsResponsePostsNodesItemContentType } from './PaginatedGetPostsResponsePostsNodesItemContentType';

/**
 * Node Content
 */
export type PaginatedGetPostsResponsePostsNodesItemContent = {
  /** 게시물 내용의 일반 텍스트 미리보기 */
  preview: string;
  /**
   * 게시물 커버 이미지 URL (없으면 없음)
   * @nullable
   */
  coverImageUrl?: string | null;
  /** 소속 프로젝트 정보 */
  project?: PaginatedGetPostsResponsePostsNodesItemContentProject;
  /** Number of Likes */
  likeCount: number;
  /** Post Type */
  type: PaginatedGetPostsResponsePostsNodesItemContentType;
  /**
   * Post Title
   * @nullable
   */
  title?: string | null;
  /** Whether the current user liked this post */
  liked: boolean;
  /** Whether the requesting user is the author of this post */
  isAuthor: boolean;
  /**
   * 게시글이 프로젝트 대시보드에 고정된 시각 (고정되지 않은 경우 없음)
   * @nullable
   */
  pinnedAt?: string | null;
  /** Creation Timestamp */
  createdAt: string;
  /** 구인글 메타데이터 (일반 게시글에는 없음) */
  recruitment?: PaginatedGetPostsResponsePostsNodesItemContentRecruitment;
  /** 게시글 공개 범위 */
  scope: PaginatedGetPostsResponsePostsNodesItemContentScope;
  /** 게시물에 첨부된 전체 미디어 수 */
  mediaCount: number;
  /** 요청자가 이 게시글을 삭제할 수 있는지 여부 (작성자, 플랫폼 관리자(개인 게시글), 프로젝트 관리자(프로젝트 게시글)) */
  canDelete: boolean;
  /** 요청자가 이 게시글에 댓글을 작성할 수 있는지 여부 (프로젝트 게시글은 팀원만 가능) */
  canComment: boolean;
  /** Post ID */
  id: number;
  /** Post Slug */
  slug: string;
  /** Last Updated Timestamp */
  updatedAt: string;
  /** Whether the question post has been resolved */
  resolved: boolean;
  /** 게시물 본문의 단어 수 */
  wordCount: number;
  /** 요청자의 열람 수준 (FULL: 본문까지 열람, PREVIEW: 유료 게이트로 본문 잠김) */
  accessLevel: PaginatedGetPostsResponsePostsNodesItemContentAccessLevel;
  /**
   * 이 글을 만든 에이전트 클라이언트의 이름. 사람이 직접 쓴 글에는 없다
   * @nullable
   */
  createdViaClientName?: string | null;
  /** Whether the current user bookmarked this post */
  bookmarked: boolean;
  /** 작성자 정보 */
  author: PaginatedGetPostsResponsePostsNodesItemContentAuthor;
  /** 게시물에 달린 태그 목록 */
  tags: PaginatedGetPostsResponsePostsNodesItemContentTagsItem[];
  /** Number of Comments */
  commentCount: number;
  /** 게시글이 어떤 시리즈에 속해 있는지 여부 */
  isSeriesPost: boolean;
  /** 미리보기용 첨부 이미지 목록 (최대 3개). 이미지가 아닌 첨부 파일은 포함되지 않는다 */
  previewMedia: PaginatedGetPostsResponsePostsNodesItemContentPreviewMediaItem[];
  /** Post Status */
  status: PaginatedGetPostsResponsePostsNodesItemContentStatus;
};
