/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 고용 형태
 * @nullable
 */
export type PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType =

    | (typeof PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType)[keyof typeof PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType]
    | null;

export const PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType =
  {
    FullTime: 'FULL_TIME',
    PartTime: 'PART_TIME',
    Contract: 'CONTRACT',
    Internship: 'INTERNSHIP',
    FreelanceProject: 'FREELANCE_PROJECT',
  } as const;
