/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 근무 방식
 * @nullable
 */
export type PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode =
  | (typeof PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode)[keyof typeof PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode]
  | null;

export const PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode =
  {
    Remote: 'REMOTE',
    Hybrid: 'HYBRID',
    Onsite: 'ONSITE',
  } as const;
