/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType } from './PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType';
import type { PaginatedGetPostsResponsePostsNodesItemContentRecruitmentExperienceLevel } from './PaginatedGetPostsResponsePostsNodesItemContentRecruitmentExperienceLevel';
import type { PaginatedGetPostsResponsePostsNodesItemContentRecruitmentStatus } from './PaginatedGetPostsResponsePostsNodesItemContentRecruitmentStatus';
import type { PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode } from './PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode';

/**
 * 구인글 메타데이터 (일반 게시글에는 없음)
 */
export type PaginatedGetPostsResponsePostsNodesItemContentRecruitment = {
  /**
   * 경력 수준
   * @nullable
   */
  experienceLevel?: PaginatedGetPostsResponsePostsNodesItemContentRecruitmentExperienceLevel;
  /**
   * 근무 방식
   * @nullable
   */
  workMode?: PaginatedGetPostsResponsePostsNodesItemContentRecruitmentWorkMode;
  /**
   * 고용 형태
   * @nullable
   */
  employmentType?: PaginatedGetPostsResponsePostsNodesItemContentRecruitmentEmploymentType;
  /**
   * 근무 지역
   * @nullable
   */
  location?: string | null;
  /**
   * 모집 마감 시각
   * @nullable
   */
  closesAt?: string | null;
  /**
   * 모집 상태
   * @nullable
   */
  status?: PaginatedGetPostsResponsePostsNodesItemContentRecruitmentStatus;
};
