/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

export type SearchUsersResponseUsersItem = {
  /** 사용자 이름 */
  name: string;
  /** 사용자 핸들 */
  handle: string;
  /** 프로필 이미지 URL */
  profileImageUrl: string;
};
