/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 고용 형태
 */
export type UpdateRecruitmentPostRequestEmploymentType =
  (typeof UpdateRecruitmentPostRequestEmploymentType)[keyof typeof UpdateRecruitmentPostRequestEmploymentType];

export const UpdateRecruitmentPostRequestEmploymentType = {
  FullTime: 'FULL_TIME',
  PartTime: 'PART_TIME',
  Contract: 'CONTRACT',
  Internship: 'INTERNSHIP',
  FreelanceProject: 'FREELANCE_PROJECT',
} as const;
