/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 모집 상태
 */
export type UpdateRecruitmentPostRequestRecruitmentStatus =
  (typeof UpdateRecruitmentPostRequestRecruitmentStatus)[keyof typeof UpdateRecruitmentPostRequestRecruitmentStatus];

export const UpdateRecruitmentPostRequestRecruitmentStatus = {
  Open: 'OPEN',
  Closed: 'CLOSED',
} as const;
