/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */
import type { UpdateRecruitmentStatusRequestStatus } from './UpdateRecruitmentStatusRequestStatus';

export interface UpdateRecruitmentStatusRequest {
  /** 변경할 모집 상태 */
  status: UpdateRecruitmentStatusRequestStatus;
}
