/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 변경할 모집 상태
 */
export type UpdateRecruitmentStatusRequestStatus =
  (typeof UpdateRecruitmentStatusRequestStatus)[keyof typeof UpdateRecruitmentStatusRequestStatus];

export const UpdateRecruitmentStatusRequestStatus = {
  Open: 'OPEN',
  Closed: 'CLOSED',
} as const;
