/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * sync
 * OpenAPI spec version: 0.0.1
 */

/**
 * 근무 방식
 */
export type UpdateRecruitmentPostRequestWorkMode =
  (typeof UpdateRecruitmentPostRequestWorkMode)[keyof typeof UpdateRecruitmentPostRequestWorkMode];

export const UpdateRecruitmentPostRequestWorkMode = {
  Remote: 'REMOTE',
  Hybrid: 'HYBRID',
  Onsite: 'ONSITE',
} as const;
